server:
  port: 8081
  shutdown: graceful

spring:
  application:
    name: catalog-service

######## Database Configuration  #########
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:15432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    open-in-view: false
######## Catalog Service Configuration  #########
catalog:
  page-size: 10

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: false
      group:
        readiness:
          show-details: always
        liveness:
          show-details: always
  info:
    git:
      mode: full
